name: Build Android APK

on:
  workflow_dispatch: 
  push:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Отримуємо ваш код
        uses: actions/checkout@v4

      - name: Встановлюємо Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Встановлюємо Java (Потрібно для Android)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Встановлюємо інструменти Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Встановлюємо стабільну версію Flet
        run: pip install flet==0.28.3

      - name: МАГІЯ! Збираємо APK файл
        run: flet build apk --product "PigStress" --org "com.roman.pigstress"

      - name: Зберігаємо готовий додаток
        uses: actions/upload-artifact@v4
        with:
          name: PigStress-Android-APK
          path: build/apk/**/*.apk
